/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testgradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        Calculator calc = new Calculator();
        System.out.println(calc.add(4, 5));
    }
}
