/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradebookentry.project;

public class App {
    public String getGreeting() {
        return null;//"Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        GradebookEntry g = new GradebookEntry("Z", 100, 80, 83);

        System.out.println(g.getName());
    }
}
